name: Docs

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "docs-${{ github.ref }}"

jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Compile sphinx docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/docs_compile"
      - name: Upload sphinx docs
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs
          path: docs/docs_compile/_build/html/
  pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy docs
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - name: Download sphinx docs
        uses: actions/download-artifact@v4
        with:
          name: sphinx-docs
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: ./docs/docs_compile/_build/html/
