name: Docs

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/docs_compile"
      - uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs
          path: docs/docs_compile/_build/html/
  pages:
    name: Deploy docs
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sphinx-docs
          path: docs/docs_compile/_build/html/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/docs_compile/_build/html/
